name: contract_pattern_sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  collection:
  rxdart:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed:
  freezed_annotation:

  dio:
  pretty_dio_logger:
  retrofit:

  gap:
  sliver_tools:
  device_preview:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:
  json_serializable:
  riverpod_generator:
  retrofit_generator:

flutter:
  uses-material-design: true
